{{- range $name, $connector := .Values.connectors }}
{{- if $connector.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "glovebox.fullname" $ }}-{{ $name }}-config
  labels:
    {{- include "glovebox.labels" $ | nindent 4 }}
    app.kubernetes.io/component: connector
    glovebox.io/connector: {{ $name }}
data:
  config.json: |
    {{- $connector.config | toJson | nindent 4 }}
{{- end }}
{{- end }}
