{{- range $name, $connector := .Values.connectors }}
{{- if $connector.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "glovebox.fullname" $ }}-{{ $name }}
  labels:
    {{- include "glovebox.labels" $ | nindent 4 }}
    app.kubernetes.io/component: connector
    glovebox.io/connector: {{ $name }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: health
      protocol: TCP
      name: health
  selector:
    app.kubernetes.io/name: {{ include "glovebox.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: connector
    glovebox.io/connector: {{ $name }}
{{- end }}
{{- end }}
