{{- range $name, $connector := .Values.connectors }}
{{- if $connector.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "glovebox.fullname" $ }}-{{ $name }}-config
  labels:
    app: glovebox-connector
    connector: {{ $name }}
    release: {{ $.Release.Name }}
data:
  config.json: |
    {{- $connector.config | toJson | nindent 4 }}
{{- end }}
{{- end }}
