{{- if .Values.config.ingest.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "glovebox.fullname" . }}-ingest
  labels:
    {{- include "glovebox.labels" . | nindent 4 }}
    app.kubernetes.io/component: scanner
spec:
  type: ClusterIP
  ports:
    {{- if include "glovebox.ingestPortServed" . }}
    - port: {{ .Values.config.ingest.port }}
      targetPort: ingest
      protocol: TCP
      name: ingest
    {{- end }}
    {{- if include "glovebox.bearerPortServed" . }}
    - port: {{ include "glovebox.bearerPort" . }}
      targetPort: ingest-bearer
      protocol: TCP
      name: ingest-bearer
    {{- end }}
    {{- if ne .Values.ingest.tls.mode "disabled" }}
    - port: {{ .Values.ingest.tls.port }}
      targetPort: ingest-tls
      protocol: TCP
      name: ingest-tls
    {{- end }}
  selector:
    {{- include "glovebox.selectorLabels" . | nindent 4 }}
{{- end }}
