{{- if .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-glovebox
  labels:
    app: glovebox
    release: {{ .Release.Name }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: glovebox
      release: {{ .Release.Name }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      path: /metrics
---
{{- range $name, $connector := .Values.connectors }}
{{- if $connector.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "glovebox.fullname" $ }}-{{ $name }}
  labels:
    app: glovebox-connector
    connector: {{ $name }}
    release: {{ $.Release.Name }}
    {{- with $.Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: glovebox-connector
      connector: {{ $name }}
      release: {{ $.Release.Name }}
  endpoints:
    - port: health
      interval: {{ $.Values.metrics.serviceMonitor.interval }}
      path: /metrics
---
{{- end }}
{{- end }}
{{- end }}
