apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mbox-importer-pvc.pvcName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "mbox-importer-pvc.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    {{- range .Values.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.size | quote }}
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass | quote }}
  {{- end }}
